# Generated by Django 4.2.2 on 2023-06-06 19:49

import django.core.validators
from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Username doesn't comply", regex='^\\w{4,20}$')])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Password doesn't comply", regex='[\\w@$!%*?&]{4,20}')])),
                ('email', models.CharField(max_length=50, unique=True, validators=[users.models.validate_real_email])),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
